environment                         = "dev"
lambda_function_name                = "dev-us-east-1-beca-2026-lambda-pokeapi"
s3_bucket_name                      = "dev-us-east-1-beca-2026-bucket-pokeapi"
lz_bronze_glue_job_name_pokeapi     = "dev-us-east-1-beca-2026-glue-job-lz-bronze-pokeapi"
bronze_silver_glue_job_name_pokeapi = "dev-us-east-1-beca-2026-glue-job-bronze-silver-pokeapi"
step_function_name                  = "dev-us-east-1-beca-2026-step-function-pokeapi"
