name: "Develop Workflow"

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/00-terraform.yml
    with:
      environment: "dev"
    secrets:
      AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_STATEFILE_S3_BUCKET: ${{ secrets.AWS_STATEFILE_S3_BUCKET }}
      AWS_LOCK_DYNAMODB_TABLE: ${{ secrets.AWS_LOCK_DYNAMODB_TABLE }}
